version: "3"
services:
  api:
    build:
      context: ./
      dockerfile: dockerfiles/node-lts
    container_name: api
    ports:
      - "5000:5000"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5000/ || exit 1
      interval: 30s
      timeout: 10s
      retries: 6
      start_period: 2m
    restart: unless-stopped
    volumes:
      - "./app:/app"

networks:
  default:
    external:
      name: nebulosa-dev
